version: '3'
services:
    nodejs:
        build: .
        restart: unless-stopped
        container_name: fit_amm_node
        volumes:
            - /app/node_modules
            - .:/app
        networks: 
          - front

    mongo:
      image: mongo:latest
      restart: unless-stopped
      container_name: fit_amm_mongo
      volumes:
        - mongodb_data_container:/data/db
      networks: 
        - front

volumes:
  mongodb_data_container:

networks:
  front:
    external:
      name: nginx