version: '3'
services:
    nodejs:
        build: .
        container_name: fit_amm_node
        ports:
            - 3000:3000
        volumes:
            - /app/node_modules
            - .:/app

    mongo:
      image: mongo:latest
      container_name: fit_amm_mongo
      volumes:
        - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: