version: '3'
services:
    nodejs:
        build: .
        restart: unless-stopped
        container_name: fit_amm_node
        volumes:
            - /app/node_modules
            - .:/app

    mongo:
      image: mongo:latest
      restart: unless-stopped
      container_name: fit_amm_mongo
      volumes:
        - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: